# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := UnitTest++ Collision Angular Linear Picking Support Tessellation VirtualGo UnitTest

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

UnitTest++: 
	@echo "==== Building UnitTest++ ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile

Collision: 
	@echo "==== Building Collision ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Collision.make

Angular: 
	@echo "==== Building Angular ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Angular.make

Linear: 
	@echo "==== Building Linear ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Linear.make

Picking: 
	@echo "==== Building Picking ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Picking.make

Support: 
	@echo "==== Building Support ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Support.make

Tessellation: 
	@echo "==== Building Tessellation ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Tessellation.make

VirtualGo: 
	@echo "==== Building VirtualGo ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f VirtualGo.make

UnitTest: UnitTest++
	@echo "==== Building UnitTest ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f UnitTest.make

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Collision.make clean
	@${MAKE} --no-print-directory -C . -f Angular.make clean
	@${MAKE} --no-print-directory -C . -f Linear.make clean
	@${MAKE} --no-print-directory -C . -f Picking.make clean
	@${MAKE} --no-print-directory -C . -f Support.make clean
	@${MAKE} --no-print-directory -C . -f Tessellation.make clean
	@${MAKE} --no-print-directory -C . -f VirtualGo.make clean
	@${MAKE} --no-print-directory -C . -f UnitTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   UnitTest++"
	@echo "   Collision"
	@echo "   Angular"
	@echo "   Linear"
	@echo "   Picking"
	@echo "   Support"
	@echo "   Tessellation"
	@echo "   VirtualGo"
	@echo "   UnitTest"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
